apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-operator-dev
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://f487-2a02-169-601-0-ad64-cd7-b178-7a5b.ngrok-free.app/validate/v1testentity
    failurePolicy: Fail
    matchPolicy: Exact
    name: test.web.hook.com
    rules:
      - apiGroups:
          - webhook.dev
        apiVersions:
          - '*'
        operations:
          - '*'
        resources:
          - testentitys
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
